/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import RMI_Structures.*;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    private ImageIcon format = null;
    String fname = null;
    int s= 0;
    byte[] pimage = null;
    
    DefaultTableModel model;
    ArrayList<Product> productlist = new ArrayList<Product>();
    RMIinterface Obj;
        
    public AdminHome() {
        initComponents();
        this.setSize(1200,600);
       
        pnlManage.setVisible(true);
        pnlAddProduct.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddProduct = new javax.swing.JPanel();
        lblquantity = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        lblcategory = new javax.swing.JLabel();
        lblprodname = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        txtprodname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        selectcategory = new javax.swing.JComboBox<>();
        btadd = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        lblresult = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        lblimg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtproddescript = new javax.swing.JTextArea();
        pnlManage = new javax.swing.JPanel();
        addprod = new javax.swing.JButton();
        editprod = new javax.swing.JButton();
        deleteprod = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableProductList = new javax.swing.JTable();
        btmanageorder = new javax.swing.JButton();
        btlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAddProduct.setPreferredSize(new java.awt.Dimension(1200, 600));
        pnlAddProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblquantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblquantity.setText("Product Quantity: ");
        pnlAddProduct.add(lblquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 292, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setText("Add New Product");
        pnlAddProduct.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 22, -1, -1));

        lblprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblprice.setText("Product Price:");
        pnlAddProduct.add(lblprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        lblcategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcategory.setText("Product Category: ");
        pnlAddProduct.add(lblcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 219, -1, -1));

        lblprodname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblprodname.setText("Product Name: ");
        pnlAddProduct.add(lblprodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 78, -1, -1));
        pnlAddProduct.add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 289, 248, 33));
        pnlAddProduct.add(txtprodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 76, 248, 31));

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        pnlAddProduct.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 248, 34));

        selectcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baby Products", "Accessories", "Home Applications", "Mobile Phones" }));
        selectcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectcategoryActionPerformed(evt);
            }
        });
        pnlAddProduct.add(selectcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 216, 248, 32));

        btadd.setText("Add");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        pnlAddProduct.add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        btcancel.setText("Cancel");
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });
        pnlAddProduct.add(btcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));
        pnlAddProduct.add(lblresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 804, 221, 23));

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        pnlAddProduct.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, -1, -1));
        pnlAddProduct.add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 230, 260));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Product Description: ");
        pnlAddProduct.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 149, -1, -1));

        txtproddescript.setColumns(20);
        txtproddescript.setRows(5);
        jScrollPane1.setViewportView(txtproddescript);

        pnlAddProduct.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 125, 248, 46));

        pnlManage.setMinimumSize(new java.awt.Dimension(4634, 456));
        pnlManage.setPreferredSize(new java.awt.Dimension(1200, 600));
        pnlManage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addprod.setText("Add Product");
        addprod.setToolTipText("");
        addprod.setActionCommand("Manage Product");
        addprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addprodActionPerformed(evt);
            }
        });
        pnlManage.add(addprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 111, -1));

        editprod.setText("Edit Product");
        editprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editprodActionPerformed(evt);
            }
        });
        pnlManage.add(editprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 111, -1));

        deleteprod.setText("Delete Product");
        deleteprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteprodActionPerformed(evt);
            }
        });
        pnlManage.add(deleteprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, -1));

        TableProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Description", "Product Category", "Product Quantity", "Product Price", "Image", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableProductList);
        if (TableProductList.getColumnModel().getColumnCount() > 0) {
            TableProductList.getColumnModel().getColumn(0).setResizable(false);
            TableProductList.getColumnModel().getColumn(0).setPreferredWidth(5);
            TableProductList.getColumnModel().getColumn(1).setResizable(false);
            TableProductList.getColumnModel().getColumn(1).setPreferredWidth(30);
            TableProductList.getColumnModel().getColumn(2).setResizable(false);
            TableProductList.getColumnModel().getColumn(2).setPreferredWidth(50);
            TableProductList.getColumnModel().getColumn(3).setResizable(false);
            TableProductList.getColumnModel().getColumn(3).setPreferredWidth(20);
            TableProductList.getColumnModel().getColumn(4).setResizable(false);
            TableProductList.getColumnModel().getColumn(4).setPreferredWidth(20);
            TableProductList.getColumnModel().getColumn(5).setResizable(false);
            TableProductList.getColumnModel().getColumn(5).setPreferredWidth(20);
            TableProductList.getColumnModel().getColumn(6).setResizable(false);
            TableProductList.getColumnModel().getColumn(6).setPreferredWidth(10);
            TableProductList.getColumnModel().getColumn(7).setResizable(false);
            TableProductList.getColumnModel().getColumn(7).setPreferredWidth(5);
        }

        pnlManage.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 1030, 400));

        btmanageorder.setText("Manage Customer Order");
        btmanageorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmanageorderActionPerformed(evt);
            }
        });
        pnlManage.add(btmanageorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, -1, -1));

        btlogout.setText("Logout");
        btlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogoutActionPerformed(evt);
            }
        });
        pnlManage.add(btlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6609, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(pnlAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 4222, Short.MAX_VALUE)
                    .addContainerGap(2365, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 943, Short.MAX_VALUE)
                    .addComponent(pnlManage, javax.swing.GroupLayout.PREFERRED_SIZE, 4722, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 944, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(pnlAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 1565, Short.MAX_VALUE)
                    .addContainerGap(1529, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteprodActionPerformed
        int input = JOptionPane.showConfirmDialog(this,
            "Are you sure about removing the selected product?", "Remove confirmation ",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (input == JOptionPane.OK_OPTION) {

            ArrayList<Integer> deletingItems = new ArrayList<>();
            ArrayList<Integer> rowsToRemove = new ArrayList<>();

            for (int i = 0; i < model.getRowCount(); i++) {
                Boolean checked = (Boolean) model.getValueAt(i, 7);

                if (checked) {
                    deletingItems.add((Integer) model.getValueAt(i, 0));//get prodid
                    rowsToRemove.add(i);
                }
            }

            // Remove rows outside of the loop
            for (int i = rowsToRemove.size() - 1; i >= 0; i--) {
                model.removeRow(rowsToRemove.get(i));
            }

            //Once we have the list to delete cart item, run delete cart function
            try {
                Obj.deleteProduct(deletingItems);
            } catch (RemoteException ex) {
                Logger.getLogger(CartMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteprodActionPerformed

    private void editprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprodActionPerformed

    }//GEN-LAST:event_editprodActionPerformed

    private void addprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addprodActionPerformed
        // TODO add your handling code here:
       
        pnlAddProduct.setVisible(true);
        pnlManage.setVisible(false);

    }//GEN-LAST:event_addprodActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JFileChooser fchoser = new JFileChooser();
        fchoser.showOpenDialog(null);
        File f=fchoser.getSelectedFile();
        fname = f.getAbsolutePath();
        ImageIcon micon = new ImageIcon(fname);
        try{
            File image = new File(fname);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readnum; (readnum=fis.read(buf)) != -1;){
                baos.write(buf,0,readnum);
            }
            pimage=baos.toByteArray();
            lblimg.setIcon(resizeImage(fname, buf));
        }catch(Exception e){

        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed

       
        pnlAddProduct.setVisible(false);
        pnlManage.setVisible(true);

    }//GEN-LAST:event_btcancelActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        try {
            String result = "";
            RMIinterface Obj;

            Obj = (RMIinterface)Naming.lookup("rmi://localhost:1040/KGF");

            String prodname = txtprodname.getText();
            String proddescript = txtproddescript.getText();
            String category = selectcategory.getSelectedItem().toString();
            String quantity = txtquantity.getText();
            String price = txtprice.getText();
            //result = System.out.println("a: " + prodname);
            result = Obj.Add_New_Product(prodname, proddescript, category, quantity, price, pimage);
            lblresult.setText(result);

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btaddActionPerformed

    private void selectcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectcategoryActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void btmanageorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmanageorderActionPerformed
        CustomerOrder custorder = new CustomerOrder();
        custorder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmanageorderActionPerformed

    private void btlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogoutActionPerformed
        AdminLogin adlogin = new AdminLogin();
        adlogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlogoutActionPerformed
       
    public ImageIcon resizeImage(String imagePath, byte[] pic){
        ImageIcon myImage = null;
        if(imagePath != null){
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lblimg.getHeight(), lblimg.getWidth(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    
    TableModelListener productTableListener = new TableModelListener() {
        @Override
        public void tableChanged(TableModelEvent e) {
            // Check if the event was triggered by a cell update
            if (e.getType() == TableModelEvent.UPDATE && e.getColumn() == 1) {
                
                int row = e.getFirstRow();
                int column = e.getColumn();
                Object newQuantity = model.getValueAt(row, column);
                Object newPrice = model.getValueAt(row, column);
                String prodID = (String) model.getValueAt(row, 4);
                
                try {
                    //if ((String) newQuantity = 0) {
                        //update the specific item's quantity = 0(also meant removed)               
                        //Obj.updateProduct(prodID, newQuantity, newPrice);
                        //model.removeRow(row);

                    //} else {
                        Obj.updateProduct(prodID, (String)newQuantity, (String)newPrice);                       
                    //}

                } catch (RemoteException ex) {
                    Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableProductList;
    private javax.swing.JButton addprod;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btcancel;
    private javax.swing.JButton btlogout;
    private javax.swing.JButton btmanageorder;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton deleteprod;
    private javax.swing.JButton editprod;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcategory;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblprodname;
    private javax.swing.JLabel lblquantity;
    private javax.swing.JLabel lblresult;
    private javax.swing.JPanel pnlAddProduct;
    private javax.swing.JPanel pnlManage;
    private javax.swing.JComboBox<String> selectcategory;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextArea txtproddescript;
    private javax.swing.JTextField txtprodname;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
