/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import RMI_Structures.*;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    private ImageIcon format = null;
    String fname = null;
    int s= 0;
    byte[] pimage = null;
    
    DefaultTableModel model;
    ArrayList<Product> productlist = new ArrayList<Product>();
    RMIinterface Obj;
        
    public AdminHome() {
        initComponents();
        this.setSize(1200,600);
        pnlMain.setVisible(true);
        pnlManage.setVisible(false);
        pnlAddProduct.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddProduct = new javax.swing.JPanel();
        lblquantity = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        lblcategory = new javax.swing.JLabel();
        lblprodname = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        txtprodname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        selectcategory = new javax.swing.JComboBox<>();
        btadd = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        lblresult = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        lblimg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtproddescript = new javax.swing.JTextArea();
        pnlManage = new javax.swing.JPanel();
        addprod = new javax.swing.JButton();
        editprod = new javax.swing.JButton();
        deleteprod = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableProductList = new javax.swing.JTable();
        pnlMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manageprod = new javax.swing.JButton();
        managecustorder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAddProduct.setPreferredSize(new java.awt.Dimension(1200, 600));

        lblquantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblquantity.setText("Product Quantity: ");

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setText("Add New Product");

        lblprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblprice.setText("Product Price:");

        lblcategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcategory.setText("Product Category: ");

        lblprodname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblprodname.setText("Product Name: ");

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        selectcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baby Products", "Accessories", "Home Applications", "Mobile Phones" }));
        selectcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectcategoryActionPerformed(evt);
            }
        });

        btadd.setText("Add");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btcancel.setText("Cancel");
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Product Description: ");

        txtproddescript.setColumns(20);
        txtproddescript.setRows(5);
        jScrollPane1.setViewportView(txtproddescript);

        javax.swing.GroupLayout pnlAddProductLayout = new javax.swing.GroupLayout(pnlAddProduct);
        pnlAddProduct.setLayout(pnlAddProductLayout);
        pnlAddProductLayout.setHorizontalGroup(
            pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddProductLayout.createSequentialGroup()
                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddProductLayout.createSequentialGroup()
                        .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddProductLayout.createSequentialGroup()
                                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAddProductLayout.createSequentialGroup()
                                        .addGap(278, 278, 278)
                                        .addComponent(lblresult, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddProductLayout.createSequentialGroup()
                                        .addComponent(btadd)
                                        .addGap(8, 8, 8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddProductLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblcategory)
                                    .addComponent(lblquantity)
                                    .addComponent(lblprice)
                                    .addComponent(jLabel3)
                                    .addComponent(lblprodname))
                                .addGap(162, 162, 162)))
                        .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addGroup(pnlAddProductLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(btcancel))
                            .addComponent(txtprodname)
                            .addComponent(selectcategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtquantity)
                            .addComponent(txtprice)))
                    .addGroup(pnlAddProductLayout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(jLabel2)))
                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddProductLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                        .addComponent(btnUpload)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddProductLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlAddProductLayout.setVerticalGroup(
            pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddProductLayout.createSequentialGroup()
                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddProductLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pnlAddProductLayout.createSequentialGroup()
                        .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddProductLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2))
                            .addGroup(pnlAddProductLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtprodname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblprodname))
                                .addGap(18, 18, 18)
                                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(45, 45, 45)
                                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblcategory)
                                    .addComponent(selectcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblquantity)
                                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblprice))
                        .addGap(46, 46, 46)))
                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btadd)
                        .addComponent(btcancel))
                    .addComponent(btnUpload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblresult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        addprod.setText("Add Product");
        addprod.setToolTipText("");
        addprod.setActionCommand("Manage Product");
        addprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addprodActionPerformed(evt);
            }
        });

        editprod.setText("Edit Product");

        deleteprod.setText("Delete Product");
        deleteprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteprodActionPerformed(evt);
            }
        });

        TableProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Description", "Product Category", "Product Quantity", "Product Price", "Image", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableProductList);
        if (TableProductList.getColumnModel().getColumnCount() > 0) {
            TableProductList.getColumnModel().getColumn(0).setResizable(false);
            TableProductList.getColumnModel().getColumn(0).setPreferredWidth(10);
            TableProductList.getColumnModel().getColumn(1).setResizable(false);
            TableProductList.getColumnModel().getColumn(1).setPreferredWidth(30);
            TableProductList.getColumnModel().getColumn(2).setResizable(false);
            TableProductList.getColumnModel().getColumn(2).setPreferredWidth(50);
            TableProductList.getColumnModel().getColumn(3).setResizable(false);
            TableProductList.getColumnModel().getColumn(3).setPreferredWidth(20);
            TableProductList.getColumnModel().getColumn(4).setResizable(false);
            TableProductList.getColumnModel().getColumn(4).setPreferredWidth(20);
            TableProductList.getColumnModel().getColumn(5).setResizable(false);
            TableProductList.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        javax.swing.GroupLayout pnlManageLayout = new javax.swing.GroupLayout(pnlManage);
        pnlManage.setLayout(pnlManageLayout);
        pnlManageLayout.setHorizontalGroup(
            pnlManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(pnlManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                    .addGroup(pnlManageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addprod, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(editprod, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(deleteprod)))
                .addGap(112, 112, 112))
        );
        pnlManageLayout.setVerticalGroup(
            pnlManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editprod)
                    .addComponent(addprod)
                    .addComponent(deleteprod))
                .addGap(144, 144, 144))
        );

        pnlMain.setPreferredSize(new java.awt.Dimension(1200, 600));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel1.setText("Admin Dashboard");

        manageprod.setFont(new java.awt.Font("Snap ITC", 3, 18)); // NOI18N
        manageprod.setText("Manage Product");
        manageprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageprodActionPerformed(evt);
            }
        });

        managecustorder.setFont(new java.awt.Font("Snap ITC", 3, 18)); // NOI18N
        managecustorder.setText("Manage Customer Order");
        managecustorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managecustorderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel1))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(manageprod)
                        .addGap(212, 212, 212)
                        .addComponent(managecustorder)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(347, 347, 347)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageprod)
                    .addComponent(managecustorder))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(pnlAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addComponent(pnlManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(pnlAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageprodActionPerformed
        // TODO add your handling code here:
        pnlMain.setVisible(false);
        pnlAddProduct.setVisible(false);
        pnlManage.setVisible(true);
         
        try {

            Obj = (RMIinterface) Naming.lookup("rmi://localhost:1040/KGF");
            productlist = Obj.getProducts();
            
            String prodName, Quantity, Price, Description, Category;
            int ID;
            byte[] image;
            boolean select = false;
            
            DefaultTableModel model = (DefaultTableModel) TableProductList.getModel();
            model.setRowCount(0);
        
            for (int i = 0; i < productlist.size(); i++) {
                ID = productlist.get(i).getID();
                prodName = productlist.get(i).getName();
                Category = productlist.get(i).getCategory();
                Description = productlist.get(i).getDescript();
                Quantity = productlist.get(i).getQuantity();
                Price = productlist.get(i).getPrice();
                image = productlist.get(i).getImage();

                Object rowData[] = {ID, prodName, Description, Category, Quantity, Price, image, select};

                model = (DefaultTableModel) TableProductList.getModel();
                model.addRow(rowData);
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_manageprodActionPerformed

    private void managecustorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managecustorderActionPerformed
        CustomerOrder custorder = new CustomerOrder();
        custorder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_managecustorderActionPerformed

    private void addprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addprodActionPerformed
        // TODO add your handling code here:
        pnlMain.setVisible(false);
        pnlAddProduct.setVisible(true);
        pnlManage.setVisible(false);
    }//GEN-LAST:event_addprodActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void selectcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectcategoryActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
    try {
            String result = "";
            RMIinterface Obj;
       
            Obj = (RMIinterface)Naming.lookup("rmi://localhost:1040/KGF");
        
            String prodname = txtprodname.getText();
            String proddescript = txtproddescript.getText();
            String category = selectcategory.getSelectedItem().toString();
            String quantity = txtquantity.getText();
            String price = txtprice.getText();
            //result = System.out.println("a: " + prodname);
            result = Obj.Add_New_Product(prodname, proddescript, category, quantity, price, pimage);
            lblresult.setText(result);
            
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                    Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
                }

        AdminHome adhome = new AdminHome();
        adhome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btaddActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed

        AdminHome adhome = new AdminHome();
        adhome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcancelActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
       JFileChooser fchoser = new JFileChooser();
       fchoser.showOpenDialog(null);
       File f=fchoser.getSelectedFile();
       fname = f.getAbsolutePath();
       ImageIcon micon = new ImageIcon(fname);
       try{
           File image = new File(fname);
           FileInputStream fis = new FileInputStream(image);
           ByteArrayOutputStream baos = new ByteArrayOutputStream();
           byte[] buf = new byte[1024];
           for(int readnum; (readnum=fis.read(buf)) != -1;){
               baos.write(buf,0,readnum);
           }
           pimage=baos.toByteArray();
           lblimg.setIcon(resizeImage(fname, buf));
       }catch(Exception e){
           
       }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void deleteprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteprodActionPerformed
        int input = JOptionPane.showConfirmDialog(this,
                "Are you sure about removing the selected product?", "Remove confirmation ",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
       
        if (input == JOptionPane.OK_OPTION) {
            
            ArrayList<Integer> deletingItems = new ArrayList<>();
            ArrayList<Integer> rowsToRemove = new ArrayList<>();

            for (int i = 0; i < model.getRowCount(); i++) {
                Boolean checked = (Boolean) model.getValueAt(i, 7);

                if (checked) {
                    deletingItems.add((Integer) model.getValueAt(i, 0));//get prodid
                    rowsToRemove.add(i);
                }
            }

            // Remove rows outside of the loop
            for (int i = rowsToRemove.size() - 1; i >= 0; i--) {
                model.removeRow(rowsToRemove.get(i));
            }

            //Once we have the list to delete cart item, run delete cart function
            try {
                Obj.deleteProduct(deletingItems);
            } catch (RemoteException ex) {
                Logger.getLogger(CartMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteprodActionPerformed
   
            
    public ImageIcon resizeImage(String imagePath, byte[] pic){
        ImageIcon myImage = null;
        if(imagePath != null){
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lblimg.getHeight(), lblimg.getWidth(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableProductList;
    private javax.swing.JButton addprod;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btcancel;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton deleteprod;
    private javax.swing.JButton editprod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcategory;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblprodname;
    private javax.swing.JLabel lblquantity;
    private javax.swing.JLabel lblresult;
    private javax.swing.JButton managecustorder;
    private javax.swing.JButton manageprod;
    private javax.swing.JPanel pnlAddProduct;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlManage;
    private javax.swing.JComboBox<String> selectcategory;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextArea txtproddescript;
    private javax.swing.JTextField txtprodname;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
