/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import RMI_Structures.Order;
import RMI_Structures.RMIinterface;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CustomerOrder extends javax.swing.JFrame {

    /**
     * Creates new form CustomerOrder
     */
    DefaultTableModel model;
    ArrayList<Order> custorderlist = new ArrayList<Order>();
    RMIinterface Obj;
    
    public CustomerOrder() {
        initComponents();
        
        try {

            Obj = (RMIinterface) Naming.lookup("rmi://localhost:1040/KGF");
            custorderlist = Obj.getCustOrders();
            
            String id,CustomerID,date,address,contact_number,payment_method,status;
            double total;
            boolean select = false;
            
            DefaultTableModel model = (DefaultTableModel) TableCustOrderList.getModel();
            model.setRowCount(0);
        
            for (int i = 0; i < custorderlist.size(); i++) {
                id = custorderlist.get(i).getOrderID();
                CustomerID = custorderlist.get(i).getCustomerID();
                date = custorderlist.get(i).getDate();
                address = custorderlist.get(i).getAddress();
                contact_number = custorderlist.get(i).getContact_number();
                payment_method = custorderlist.get(i).getPayment();
                status = custorderlist.get(i).getStatus();
                total = custorderlist.get(i).getTotal();

                Object rowData[] = {id,CustomerID,total,date,address,contact_number,payment_method,status,};

                model = (DefaultTableModel) TableCustOrderList.getModel();
                model.addRow(rowData);
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableCustOrderList = new javax.swing.JTable();
        btback = new javax.swing.JButton();
        btstatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1200, 600));

        TableCustOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order No", "Customer ID", "Total", "Date", "Address", "Contact Number", "Payment Method", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableCustOrderList);
        if (TableCustOrderList.getColumnModel().getColumnCount() > 0) {
            TableCustOrderList.getColumnModel().getColumn(0).setResizable(false);
            TableCustOrderList.getColumnModel().getColumn(1).setResizable(false);
            TableCustOrderList.getColumnModel().getColumn(2).setResizable(false);
            TableCustOrderList.getColumnModel().getColumn(3).setResizable(false);
            TableCustOrderList.getColumnModel().getColumn(4).setResizable(false);
            TableCustOrderList.getColumnModel().getColumn(5).setResizable(false);
            TableCustOrderList.getColumnModel().getColumn(6).setResizable(false);
            TableCustOrderList.getColumnModel().getColumn(7).setResizable(false);
        }

        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        btstatus.setText("Update Status");
        btstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btstatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btback)
                        .addGap(38, 38, 38)
                        .addComponent(btstatus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btback)
                    .addComponent(btstatus))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
       AdminHome adhome = new AdminHome();
       adhome.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btbackActionPerformed

    private void btstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btstatusActionPerformed
        try {
            int column = 0;
            int row = TableCustOrderList.getSelectedRow();
            String orderno = TableCustOrderList.getModel().getValueAt(row, column).toString();

            EditCustOrderStatus ecos = new EditCustOrderStatus(Obj.displayCustOrderStatus(orderno));
            ecos.setVisible(true);
            this.dispose();
            
        } catch (RemoteException ex) {
            Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCustOrderList;
    private javax.swing.JButton btback;
    private javax.swing.JButton btstatus;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
