package views;

import RMI_Structures.*;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class LoginRegister extends javax.swing.JFrame {

    /**
     * Creates new form clientGUI
     */
    public LoginRegister() {
        initComponents();
        this.setSize(1200,600);
        pnlRegister.setVisible(false);
        pnlLogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblEmailLogin = new javax.swing.JLabel();
        txtEmailLogin = new javax.swing.JTextField();
        lblPasswordLogin = new javax.swing.JLabel();
        txtPasswordLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        lblLoginResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlRegister = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextArea();
        lblEmail = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextArea();
        btnCreate = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        lblUsername = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        lblPasswordsResult = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        lblLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblLogin.setText("Login");

        lblEmailLogin.setText("Email");

        txtEmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailLoginActionPerformed(evt);
            }
        });

        lblPasswordLogin.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlLoginLayout.createSequentialGroup()
                            .addComponent(lblEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlLoginLayout.createSequentialGroup()
                            .addComponent(lblPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPasswordLogin)
                                .addGroup(pnlLoginLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(btnLogin)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSignUp)))))
                    .addComponent(lblLoginResult, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginResult, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnSignUp))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogin);
        pnlLogin.setBounds(350, 90, 590, 400);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1170, 0, 30, 50);

        pnlRegister.setLayout(null);

        lblRegister.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblRegister.setText("Register");
        pnlRegister.add(lblRegister);
        lblRegister.setBounds(10, 10, 250, 50);

        txtEmail.setColumns(20);
        txtEmail.setRows(5);
        txtEmail.setName("txtUsername"); // NOI18N
        pnlRegister.add(txtEmail);
        txtEmail.setBounds(140, 80, 272, 34);

        lblEmail.setText("Email");
        lblEmail.setName("lblRadius"); // NOI18N
        pnlRegister.add(lblEmail);
        lblEmail.setBounds(20, 80, 92, 34);
        lblEmail.getAccessibleContext().setAccessibleName("lblRadius\n");

        txtUsername.setColumns(20);
        txtUsername.setRows(5);
        txtUsername.setName("txtUsername"); // NOI18N
        pnlRegister.add(txtUsername);
        txtUsername.setBounds(140, 140, 272, 34);
        txtUsername.getAccessibleContext().setAccessibleName("");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        pnlRegister.add(btnCreate);
        btnCreate.setBounds(140, 330, 72, 23);

        lblResult.setText("  ");
        pnlRegister.add(lblResult);
        lblResult.setBounds(140, 310, 270, 20);
        pnlRegister.add(txtPassword);
        txtPassword.setBounds(140, 200, 272, 34);

        lblPassword.setText("Password");
        lblPassword.setName("lblRadius"); // NOI18N
        pnlRegister.add(lblPassword);
        lblPassword.setBounds(20, 200, 92, 34);

        txtConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordActionPerformed(evt);
            }
        });
        txtConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfirmPasswordKeyTyped(evt);
            }
        });
        pnlRegister.add(txtConfirmPassword);
        txtConfirmPassword.setBounds(140, 250, 272, 34);

        lblUsername.setText("Username");
        lblUsername.setName("lblRadius"); // NOI18N
        pnlRegister.add(lblUsername);
        lblUsername.setBounds(20, 140, 92, 34);

        lblConfirmPassword.setText("Confirm Password");
        lblConfirmPassword.setName("lblRadius"); // NOI18N
        pnlRegister.add(lblConfirmPassword);
        lblConfirmPassword.setBounds(20, 250, 140, 34);

        lblPasswordsResult.setText("  ");
        pnlRegister.add(lblPasswordsResult);
        lblPasswordsResult.setBounds(140, 290, 270, 20);

        btnBack.setText("Login");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlRegister.add(btnBack);
        btnBack.setBounds(230, 330, 72, 23);

        getContentPane().add(pnlRegister);
        pnlRegister.setBounds(370, 120, 510, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try {
            String result = "";
            RMIinterface Obj = (RMIinterface)Naming.lookup("rmi://localhost:1040/KGF");
            String name = txtUsername.getText();
            String password = txtPassword.getText();  
            String Cpassword = txtConfirmPassword.getText();
            String email = txtEmail.getText();
            if(password.equals(Cpassword)){
                 result = Obj.customer_register(email, name,password);
            }else{
                result = "Mismatched Passwords";
            }
            lblResult.setText(result);
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(LoginRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void txtConfirmPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPasswordKeyTyped
        
        
    }//GEN-LAST:event_txtConfirmPasswordKeyTyped

    private void txtConfirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPasswordKeyReleased
       if(txtPassword.getText().equals(txtConfirmPassword.getText())){
            lblPasswordsResult.setText("Both passwords are matched");
        }else{
            lblPasswordsResult.setText("Passwords not matched");
        }        
    }//GEN-LAST:event_txtConfirmPasswordKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        pnlRegister.setVisible(false);
        pnlLogin.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailLoginActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String email = txtEmailLogin.getText();
        String passwords = txtPasswordLogin.getText();
        try {
            RMIinterface Obj = (RMIinterface)Naming.lookup("rmi://localhost:1040/KGF");
           if(Obj.customer_login(email, passwords)){
                lblLoginResult.setText("you are logged in.");
                Customer cm = Obj.customer_setup(email);
                Home hm = new Home(cm);
                hm.setVisible(true);
                this.dispose();
            }else{
                lblLoginResult.setText("Incorrect email or passwords.");
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(LoginRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(LoginRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(LoginRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        pnlRegister.setVisible(true);
        pnlLogin.setVisible(false);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);   
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailLogin;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLoginResult;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordLogin;
    private javax.swing.JLabel lblPasswordsResult;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextArea txtEmail;
    private javax.swing.JTextField txtEmailLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordLogin;
    private javax.swing.JTextArea txtUsername;
    // End of variables declaration//GEN-END:variables
}
